[book]
authors = ["DigitalData"]
language = "en"
multilingual = false
src = "src"
title = "Forge Documentation"

[preprocessor.tabs]

[preprocessor.mermaid]
command = "mdbook-mermaid"

# [preprocessor.breadcrumbs]
# command = "/home/fiftin/src/semaphore/mdbook-breadcrumbs/target/release/mdbook-breadcrumbs"

[output.html]
additional-css = ["theme/tabs.css", "theme/search.css", "theme/content.css", "theme/header.css"]
additional-js = ["theme/tabs.js"] # "mermaid.min.js", "mermaid-init.js"
google-analytics = "G-SXDFVHLVBM"
edit-url-template = "https://github.com/Digital-Data-Co/forge-docs/edit/main/{path}"
site-url = "https://digital-data-co.github.io/forge-docs"

[output.html.search]
enable = true
limit-results = 10

[output.html.fold]
enable = true
level = 1